USE [master]
GO
/****** Object:  Database [Noam]    Script Date: 02/01/2023 18:55:43 ******/
CREATE DATABASE [Noam]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Noam', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS01\MSSQL\DATA\Noam.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Noam_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS01\MSSQL\DATA\Noam_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Noam] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Noam].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Noam] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Noam] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Noam] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Noam] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Noam] SET ARITHABORT OFF 
GO
ALTER DATABASE [Noam] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Noam] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Noam] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Noam] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Noam] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Noam] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Noam] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Noam] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Noam] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Noam] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Noam] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Noam] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Noam] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Noam] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Noam] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Noam] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Noam] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Noam] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Noam] SET  MULTI_USER 
GO
ALTER DATABASE [Noam] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Noam] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Noam] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Noam] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Noam] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Noam] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Noam] SET QUERY_STORE = ON
GO
ALTER DATABASE [Noam] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Noam]
GO
/****** Object:  Table [dbo].[Ingredients]    Script Date: 02/01/2023 18:55:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ingredients](
	[ingredientId] [int] IDENTITY(1,1) NOT NULL,
	[ingredientsName] [nvarchar](20) NOT NULL,
	[imgUrl] [nvarchar](200) NOT NULL,
	[calories] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ingredientId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[IngredientsInRecipes]    Script Date: 02/01/2023 18:55:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IngredientsInRecipes](
	[recipeId] [int] NOT NULL,
	[ingredientId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[recipeId] ASC,
	[ingredientId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Recipes]    Script Date: 02/01/2023 18:55:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Recipes](
	[recipeId] [int] IDENTITY(1,1) NOT NULL,
	[recipeName] [nvarchar](20) NOT NULL,
	[imgUrl] [nvarchar](200) NOT NULL,
	[cookingMethod] [nvarchar](200) NULL,
	[time] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[recipeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IngredientsInRecipes]  WITH CHECK ADD FOREIGN KEY([ingredientId])
REFERENCES [dbo].[Ingredients] ([ingredientId])
GO
ALTER TABLE [dbo].[IngredientsInRecipes]  WITH CHECK ADD FOREIGN KEY([recipeId])
REFERENCES [dbo].[Recipes] ([recipeId])
GO
USE [master]
GO
ALTER DATABASE [Noam] SET  READ_WRITE 
GO
